import { Resend } from 'resend'
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnySupabaseClient = any

const resend = new Resend(process.env.RESEND_API_KEY)
const APP_URL = process.env.NEXT_PUBLIC_APP_URL || 'https://getsuitel.com'

// Shared invite-code generation + email, used by:
//  - POST /api/hq/branches/[id]/invite (HQ admin manually generates/shares a code)
//  - the agreement sign-off flow (auto-fires once a branch's franchise
//    agreement is marked signed, if pending_superadmin_email was set)
// Keeping this in one place means both paths always produce the same code
// format, expiry, and email template — no drift between "generate manually"
// and "generate automatically."

export function generateInviteCode(): string {
  // 8 uppercase alphanumeric chars, no ambiguous O/0/I/1 pairs, formatted XXXX-XXXX
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'
  const buf = new Uint8Array(8)
  crypto.getRandomValues(buf)
  const raw = Array.from(buf).map(b => chars[b % chars.length]).join('')
  return `${raw.slice(0, 4)}-${raw.slice(4)}`
}

function inviteEmailHtml(branchName: string, code: string, inviteUrl: string, expiresDate: string): string {
  return `<!DOCTYPE html><html><head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;padding:40px 20px">
<tr><td align="center">
<table width="560" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08)">
<tr><td style="background:#1B3A6B;padding:28px 32px">
  <div style="font-size:22px;font-weight:900;color:#fff">Get<span style="color:#C9931A">Suitel</span></div>
  <div style="font-size:12px;color:rgba(255,255,255,0.6);margin-top:4px">Branch Superadmin Invitation</div>
</td></tr>
<tr><td style="padding:32px">
  <p style="font-size:16px;color:#1e293b;font-weight:700;margin:0 0 8px">You're invited to manage the <span style="color:#C9931A">${branchName}</span> branch</p>
  <p style="font-size:14px;color:#475569;line-height:1.7;margin:0 0 24px">GetSuitel HQ has signed your branch's franchise agreement. Use the invite code below to create your superadmin account.</p>
  <div style="background:#f1f5f9;border-radius:12px;padding:24px;text-align:center;margin-bottom:24px">
    <div style="font-size:11px;font-weight:600;color:#64748b;letter-spacing:0.1em;text-transform:uppercase;margin-bottom:8px">Your Invite Code</div>
    <div style="font-size:36px;font-weight:900;letter-spacing:0.2em;color:#1B3A6B;font-family:monospace">${code}</div>
    <div style="font-size:12px;color:#94a3b8;margin-top:8px">Expires ${expiresDate} · One-time use</div>
  </div>
  <div style="text-align:center;margin-bottom:24px">
    <a href="${inviteUrl}" style="display:inline-block;background:#C9931A;color:#fff;font-weight:700;font-size:14px;padding:14px 32px;border-radius:10px;text-decoration:none">Claim Your Account →</a>
  </div>
  <p style="font-size:12px;color:#94a3b8;line-height:1.6;margin:0">Or copy this link into your browser:<br/><span style="color:#1B3A6B">${inviteUrl}</span></p>
</td></tr>
<tr><td style="background:#f8fafc;padding:20px 32px;text-align:center">
  <p style="font-size:11px;color:#94a3b8;margin:0">© ${new Date().getFullYear()} GetSuitel · This invite was generated by GetSuitel HQ</p>
</td></tr>
</table>
</td></tr>
</table>
</body></html>`
}

/**
 * Generates a fresh invite code for a branch, expires any unused existing
 * codes first, and optionally emails it. Returns the code + url either way
 * so callers can also show/copy it in the UI.
 */
export async function issueBranchInvite(
  supabase: AnySupabaseClient,
  opts: { branchId: string; branchName: string; createdBy: string; email?: string | null },
): Promise<{ code: string; inviteUrl: string; expiresAt: string; emailed: boolean }> {
  const { branchId, branchName, createdBy, email } = opts

  // Expire any existing unused codes for this branch
  await supabase
    .from('invite_codes')
    .update({ expires_at: new Date().toISOString() })
    .eq('branch_id', branchId)
    .is('used_by', null)

  const code = generateInviteCode()
  const expiresAt = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000)

  const { error } = await supabase
    .from('invite_codes')
    .insert({
      code,
      branch_id: branchId,
      created_by: createdBy,
      expires_at: expiresAt.toISOString(),
    })

  if (error) throw new Error(error.message)

  const inviteUrl = `${APP_URL}/auth/invite?code=${code}`
  let emailed = false

  if (email?.trim()) {
    try {
      const expiresDate = expiresAt.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
      await resend.emails.send({
        from: 'GetSuitel <noreply@getsuitel.com>',
        to: email.trim(),
        subject: `You're invited to manage the ${branchName} branch — GetSuitel`,
        html: inviteEmailHtml(branchName, code, inviteUrl, expiresDate),
      })
      emailed = true
    } catch {
      // Email failure is non-fatal — the code still exists and can be copied/shared manually
    }
  }

  return { code, inviteUrl, expiresAt: expiresAt.toISOString(), emailed }
}
