import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { Resend } from 'resend'

const resend = new Resend(process.env.RESEND_API_KEY)
const APP_URL = process.env.NEXT_PUBLIC_APP_URL || 'https://getsuitel.com'

async function requireHQ(supabase: Awaited<ReturnType<typeof createClient>>) {
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return null
  const { data: profile } = await supabase.from('profiles').select('role').eq('id', user.id).single()
  if (profile?.role !== 'hq_admin') return null
  return user
}

function generateCode(): string {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'
  const buf = new Uint8Array(8)
  crypto.getRandomValues(buf)
  const raw = Array.from(buf).map(b => chars[b % chars.length]).join('')
  return `${raw.slice(0, 4)}-${raw.slice(4)}`
}

function inviteEmailHtml(branchName: string, code: string, inviteUrl: string, expiresDate: string): string {
  return `<!DOCTYPE html><html><head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;padding:40px 20px">
<tr><td align="center">
<table width="560" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08)">
<tr><td style="background:#1B3A6B;padding:28px 32px">
  <div style="font-size:22px;font-weight:900;color:#fff">Get<span style="color:#C9931A">Suitel</span></div>
  <div style="font-size:12px;color:rgba(255,255,255,0.6);margin-top:4px">Branch Superadmin Invitation</div>
</td></tr>
<tr><td style="padding:32px">
  <p style="font-size:16px;color:#1e293b;font-weight:700;margin:0 0 8px">You're invited to manage the <span style="color:#C9931A">${branchName}</span> branch</p>
  <p style="font-size:14px;color:#475569;line-height:1.7;margin:0 0 24px">GetSuitel HQ has set up a branch for your region. Use the invite code below to create your superadmin account.</p>
  <div style="background:#f1f5f9;border-radius:12px;padding:24px;text-align:center;margin-bottom:24px">
    <div style="font-size:11px;font-weight:600;color:#64748b;letter-spacing:0.1em;text-transform:uppercase;margin-bottom:8px">Your Invite Code</div>
    <div style="font-size:36px;font-weight:900;letter-spacing:0.2em;color:#1B3A6B;font-family:monospace">${code}</div>
    <div style="font-size:12px;color:#94a3b8;margin-top:8px">Expires ${expiresDate} · One-time use</div>
  </div>
  <div style="text-align:center;margin-bottom:24px">
    <a href="${inviteUrl}" style="display:inline-block;background:#C9931A;color:#fff;font-weight:700;font-size:14px;padding:14px 32px;border-radius:10px;text-decoration:none">Claim Your Account →</a>
  </div>
  <p style="font-size:12px;color:#94a3b8;line-height:1.6;margin:0">Or copy this link into your browser:<br/><span style="color:#1B3A6B">${inviteUrl}</span></p>
</td></tr>
<tr><td style="background:#f8fafc;padding:20px 32px;text-align:center">
  <p style="font-size:11px;color:#94a3b8;margin:0">© ${new Date().getFullYear()} GetSuitel · This invite was generated by GetSuitel HQ</p>
</td></tr>
</table>
</td></tr>
</table>
</body></html>`
}

export async function GET() {
  const supabase = await createClient()
  if (!await requireHQ(supabase)) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { data, error } = await supabase
    .from('branches')
    .select('*, profiles!branches_superadmin_id_fkey(full_name, email)')
    .order('created_at', { ascending: false })

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  return NextResponse.json(data)
}

export async function POST(req: NextRequest) {
  const supabase = await createClient()
  const user = await requireHQ(supabase)
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const body = await req.json()
  const { name, region, city, status, license_fee_omr, revenue_share_pct, superadmin_id, logo_url, superadmin_email } = body

  if (!name?.trim()) return NextResponse.json({ error: 'Branch name is required' }, { status: 400 })

  const { data, error } = await supabase
    .from('branches')
    .insert({ name: name.trim(), region, city, status, license_fee_omr, revenue_share_pct, superadmin_id, logo_url })
    .select()
    .single()

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  // Auto-send invite if email provided
  if (superadmin_email?.trim()) {
    try {
      const code = generateCode()
      const expiresAt = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000)
      await supabase.from('invite_codes').insert({
        code,
        branch_id: data.id,
        created_by: user.id,
        expires_at: expiresAt.toISOString(),
      })
      const inviteUrl = `${APP_URL}/auth/invite?code=${code}`
      const expiresDate = expiresAt.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
      const branchName = data.display_name ?? data.name
      await resend.emails.send({
        from: 'GetSuitel <noreply@getsuitel.com>',
        to: superadmin_email.trim(),
        subject: `You're invited to manage the ${branchName} branch — GetSuitel`,
        html: inviteEmailHtml(branchName, code, inviteUrl, expiresDate),
      })
    } catch {
      // Email failure is non-fatal — branch is already created
    }
  }

  return NextResponse.json({ ...data, invite_sent: !!superadmin_email?.trim() }, { status: 201 })
}

export async function PATCH(req: NextRequest) {
  const supabase = await createClient()
  if (!await requireHQ(supabase)) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const body = await req.json()
  // Strip superadmin_email — it's used only for invite sending, not a DB column
  const { id, superadmin_email: _ignored, ...updates } = body
  if (!id) return NextResponse.json({ error: 'Branch ID required' }, { status: 400 })

  const { data, error } = await supabase
    .from('branches')
    .update({ ...updates, updated_at: new Date().toISOString() })
    .eq('id', id)
    .select()
    .single()

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  return NextResponse.json(data)
}

export async function DELETE(req: NextRequest) {
  const supabase = await createClient()
  if (!await requireHQ(supabase)) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { searchParams } = new URL(req.url)
  const id = searchParams.get('id')
  if (!id) return NextResponse.json({ error: 'Branch ID required' }, { status: 400 })

  const { error } = await supabase.from('branches').delete().eq('id', id)
  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  return NextResponse.json({ success: true })
}
